/*CONSTANTS ARE THE VALUES THAT CANNOT BE CHANGED
THERE ARE THREE TYPES OF CONSTANTS
1.INTEGER CONSTANTS:-
                1,2,3,-1,-2
2.REAL CONSTANTS:-
                1.0,2.0,3.14,-24
3.CHARACTER CONSTANTS:-
                'a','A','#','@'*/             